[weightclasses]

[divisions]
    open = {name = "Open", min = 0, max = 999}

[exemptions]
    1301 = ["ExemptWeightClassConsistency"]
    1401 = ["ExemptWeightClassConsistency"]
    1201 = ["ExemptWeightClassConsistency"]
