[divisions]
    # Official division names are as described in an email from the USAPL
    # National Office (nationaloffice@usapowerlifting.com), sent 2018-02-22.
    
    # Official divisions, Raw Men.
    mro = {name="MR-O", min=0, max=999, sex="M", equipment="Raw"}
    mry1 = {name="MR-Y1", min=8, max=9, sex="M", equipment="Raw"}
    mry2 = {name="MR-Y2", min=10, max=11, sex="M", equipment="Raw"}
    mry3 = {name="MR-Y3", min=12, max=13, sex="M", equipment="Raw"}
    mrt1 = {name="MR-T1", min=14, max=15, sex="M", equipment="Raw"}
    mrt2 = {name="MR-T2", min=16, max=17, sex="M", equipment="Raw"}
    mrt3 = {name="MR-T3", min=18, max=19, sex="M", equipment="Raw"}
    mrjr = {name="MR-JR", min=20, max=23, sex="M", equipment="Raw"}
    mrm1a = {name="MR-M1A", min=39.5, max=44.5, sex="M", equipment="Raw"}
    mrm1b = {name="MR-M1B", min=44.5, max=49.5, sex="M", equipment="Raw"}
    mrm2a = {name="MR-M2A", min=49.5, max=54.5, sex="M", equipment="Raw"}
    mrm2b = {name="MR-M2B", min=54.5, max=59.5, sex="M", equipment="Raw"}
    mrm3a = {name="MR-M3A", min=59.5, max=64.5, sex="M", equipment="Raw"}
    mrm3b = {name="MR-M3B", min=64.5, max=69.5, sex="M", equipment="Raw"}
    mrm4a = {name="MR-M4A", min=69.5, max=74.5, sex="M", equipment="Raw"}
    mrm4b = {name="MR-M4B", min=74.5, max=79.5, sex="M", equipment="Raw"}
    mrm5 = {name="MR-M5", min=79.5, max=999, sex="M", equipment="Raw"}
    mrg = {name="MR-G", min=0, max=999, sex="M", equipment="Raw"}

    # Official divisions, Raw Women.
    fro = {name="FR-O", min=0, max=999, sex="F", equipment="Raw"}
    fry1 = {name="FR-Y1", min=8, max=9, sex="F", equipment="Raw"}
    fry2 = {name="FR-Y2", min=10, max=11, sex="F", equipment="Raw"}
    fry3 = {name="FR-Y3", min=12, max=13, sex="F", equipment="Raw"}
    frt1 = {name="FR-T1", min=14, max=15, sex="F", equipment="Raw"}
    frt2 = {name="FR-T2", min=16, max=17, sex="F", equipment="Raw"}
    frt3 = {name="FR-T3", min=18, max=19, sex="F", equipment="Raw"}
    frjr = {name="FR-JR", min=20, max=23, sex="F", equipment="Raw"}
    frm1a = {name="FR-M1A", min=39.5, max=44.5, sex="F", equipment="Raw"}
    frm1b = {name="FR-M1B", min=44.5, max=49.5, sex="F", equipment="Raw"}
    frm2a = {name="FR-M2A", min=49.5, max=54.5, sex="F", equipment="Raw"}
    frm2b = {name="FR-M2B", min=54.5, max=59.5, sex="F", equipment="Raw"}
    frm3a = {name="FR-M3A", min=59.5, max=64.5, sex="F", equipment="Raw"}
    frm3b = {name="FR-M3B", min=64.5, max=69.5, sex="F", equipment="Raw"}
    frm4a = {name="FR-M4A", min=69.5, max=74.5, sex="F", equipment="Raw"}
    frm4b = {name="FR-M4B", min=74.5, max=79.5, sex="F", equipment="Raw"}
    frm5 = {name="FR-M5", min=79.5, max=999, sex="F", equipment="Raw"}
    frg = {name="FR-G", min=0, max=999, sex="F", equipment="Raw"}

    # Official divisions, Equipped Men.
    mo = {name="M-O", min=0, max=999, sex="M", equipment="Single-ply"}
    my1 = {name="M-Y1", min=8, max=9, sex="M", equipment="Single-ply"}
    my2 = {name="M-Y2", min=10, max=11, sex="M", equipment="Single-ply"}
    my3 = {name="M-Y3", min=12, max=13, sex="M", equipment="Single-ply"}
    mt1 = {name="M-T1", min=14, max=15, sex="M", equipment="Single-ply"}
    mt2 = {name="M-T2", min=16, max=17, sex="M", equipment="Single-ply"}
    mt3 = {name="M-T3", min=18, max=19, sex="M", equipment="Single-ply"}
    mjr = {name="M-JR", min=20, max=23, sex="M", equipment="Single-ply"}
    mm1a = {name="M-M1A", min=39.5, max=44.5, sex="M", equipment="Single-ply"}
    mm1b = {name="M-M1B", min=44.5, max=49.5, sex="M", equipment="Single-ply"}
    mm2a = {name="M-M2A", min=49.5, max=54.5, sex="M", equipment="Single-ply"}
    mm2b = {name="M-M2B", min=54.5, max=59.5, sex="M", equipment="Single-ply"}
    mm3a = {name="M-M3A", min=59.5, max=64.5, sex="M", equipment="Single-ply"}
    mm3b = {name="M-M3B", min=64.5, max=69.5, sex="M", equipment="Single-ply"}
    mm4a = {name="M-M4A", min=69.5, max=74.5, sex="M", equipment="Single-ply"}
    mm4b = {name="M-M4B", min=74.5, max=79.5, sex="M", equipment="Single-ply"}
    mm5 = {name="M-M5", min=79.5, max=999, sex="M", equipment="Single-ply"}
    mg = {name="M-G", min=0, max=999, sex="M", equipment="Single-ply"}

    # Official divisions, Equipped Women.
    fo = {name="F-O", min=0, max=999, sex="F", equipment="Single-ply"}
    fy1 = {name="F-Y1", min=8, max=9, sex="F", equipment="Single-ply"}
    fy2 = {name="F-Y2", min=10, max=11, sex="F", equipment="Single-ply"}
    fy3 = {name="F-Y3", min=12, max=13, sex="F", equipment="Single-ply"}
    ft1 = {name="F-T1", min=14, max=15, sex="F", equipment="Single-ply"}
    ft2 = {name="F-T2", min=16, max=17, sex="F", equipment="Single-ply"}
    ft3 = {name="F-T3", min=18, max=19, sex="F", equipment="Single-ply"}
    fjr = {name="F-JR", min=20, max=23, sex="F", equipment="Single-ply"}
    fm1a = {name="F-M1A", min=39.5, max=44.5, sex="F", equipment="Single-ply"}
    fm1b = {name="F-M1B", min=44.5, max=49.5, sex="F", equipment="Single-ply"}
    fm2a = {name="F-M2A", min=49.5, max=54.5, sex="F", equipment="Single-ply"}
    fm2b = {name="F-M2B", min=54.5, max=59.5, sex="F", equipment="Single-ply"}
    fm3a = {name="F-M3A", min=59.5, max=64.5, sex="F", equipment="Single-ply"}
    fm3b = {name="F-M3B", min=64.5, max=69.5, sex="F", equipment="Single-ply"}
    fm4a = {name="F-M4A", min=69.5, max=74.5, sex="F", equipment="Single-ply"}
    fm4b = {name="F-M4B", min=74.5, max=79.5, sex="F", equipment="Single-ply"}
    fm5 = {name="F-M5", min=79.5, max=999, sex="F", equipment="Single-ply"}
    fg = {name="F-G", min=0, max=999, sex="F", equipment="Single-ply"}

    # These are additional, unofficial divisions that were nevertheless used.

    RO = {name ="R-O", min=0, max=999}
    RHS = {name ="R-HS", min=13, max=19}
    RC = {name ="R-C", min=0, max=999}
    RJR = {name = "R-JR", min=0, max=23}
    RY = {name = "R-Y", min=8, max=13}
    RY1 = {name = "R-Y1", min=8, max=9}
    RY2 = {name = "R-Y2", min=10, max=11}
    RY3 = {name = "R-Y3", min=12, max=13}
    RT = {name = "R-T", min=0, max=19}
    RT1 = {name = "R-T1", min=14, max=15}
    RT2 = {name = "R-T2", min=16, max=17}
    RT3 = {name = "R-T3", min=18, max=19}
    RM1A = {name = "R-M1a", min=39.5, max=43.5}
    RM1B = {name = "R-M1b", min=44.5, max=48.5}
    RM2A = {name = "R-M2a", min=49.5, max=53.5}
    RM2B = {name = "R-M2b", min=54.5, max=58.5}
    RM3A = {name = "R-M3a", min=59.5, max=63.5}
    RM3B = {name = "R-M3b", min=64.5, max=68.5}
    RM4A = {name = "R-M4a", min=69.5, max=73.5}
    RM4B = {name = "R-M4b", min=74.5, max=78.5}
    O = {name ="O", min=0, max=999}
    C = {name ="C", min=0, max=999}
    HS = {name ="HS", min=13, max=19}
    JR = {name = "JR", min=0, max=23}
    Y = {name = "Y", min=8, max=13}
    Y1 = {name = "Y1", min=8, max=9}
    Y2 = {name = "Y2", min=10, max=11}
    Y3 = {name = "Y3", min=12, max=13}
    T = {name = "T", min=0, max=19}
    T1 = {name = "T1", min=14, max=15}
    T2 = {name = "T2", min=16, max=17}
    T3 = {name = "T3", min=18, max=19}
    M1A = {name = "M1a", min=39.5, max=43.5}
    M1B = {name = "M1b", min=44.5, max=48.5}
    M2A = {name = "M2a", min=49.5, max=53.5}
    M2B = {name = "M2b", min=54.5, max=58.5}
    M3A = {name = "M3a", min=59.5, max=63.5}
    M3B = {name = "M3b", min=64.5, max=68.5}
    M4A = {name = "M4a", min=69.5, max=73.5}
    M4B = {name = "M4b", min=74.5, max=78.5}

    #IPF Divisons
    RM1 = {name = "R-M1", min=39.5, max=48.5}
    RM2 = {name = "R-M2", min=49.5, max=58.5}
    RM3 = {name = "R-M3", min=59.5, max=68.5}
    RM4 = {name = "R-M4", min=69.5, max=999}
    M1 = {name = "M1", min=39.5, max=48.5}
    M2 = {name = "M2", min=49.5, max=58.5}
    M3 = {name = "M3", min=59.5, max=68.5}
    M4 = {name = "M4", min=69.5, max=999}

[weightclasses.default_M]
    classes = ["59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["47","52","57","63","72","84","84+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "F"

[weightclasses.junior_M]
    classes = ["53","59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"
    divisions = ["R-JR","R-T","JR","T"]

[weightclasses.junior_F]
    classes = ["43","47","52","57","63","72","84","84+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "F"
    divisions = ["R-JR","R-T","JR","T"]

[weightclasses.youth_M]
    classes = ["30","35","40","44","48","53","59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"
    divisions = ["R-Y","R-Y1","R-Y2","R-Y3","Y","Y1","Y2","Y3"]

[weightclasses.youth_F]
    classes = ["30","35","40","43","47","52","57","63","72","84","84+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "F"
    divisions = ["R-Y","R-Y1","R-Y2","R-Y3","Y","Y1","Y2","Y3"]

[weightclasses.old_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","125+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "M"

[weightclasses.old_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "F"

[exemptions]
