---
- name: make sure nginx is the latest version
  dnf:
    name: nginx
    state: latest
  notify: restart nginx

- name: copy nginx configuration
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: make sure nginx is running
  service:
    name: nginx
    state: started
    enabled: yes
