[divisions]
    #WPC divisions
    morwpc = {name ="M_O_R_WPC",min=0,max=999,equipment="Raw",sex="M"}
    mocrwpc = {name ="M_O_CR_WPC",min=0,max=999,equipment=["Raw","Wraps"],sex="M"}
    moswpc = {name ="M_O_ES_WPC",min=0,max=999,equipment="Single-ply",sex="M"}
    momwpc = {name ="M_O_EM_WPC",min=0,max=999,equipment="Multi-ply",sex="M"}
    mm1rwpc = {name ="M_M1_R_WPC",min=40,max=44,equipment="Raw",sex="M"}
    mm1crwpc = {name ="M_M1_CR_WPC",min=40,max=44,equipment=["Raw","Wraps"],sex="M"}
    mm1swpc = {name ="M_M1_ES_WPC",min=40,max=44,equipment="Single-ply",sex="M"}
    mm1mwpc = {name ="M_M1_EM_WPC",min=40,max=44,equipment="Multi-ply",sex="M"}
    mm2rwpc = {name ="M_M2_R_WPC",min=45,max=49,equipment="Raw",sex="M"}
    mm2crwpc = {name ="M_M2_CR_WPC",min=45,max=49,equipment=["Raw","Wraps"],sex="M"}
    mm2swpc = {name ="M_M2_ES_WPC",min=45,max=49,equipment="Single-ply",sex="M"}
    mm2mwpc = {name ="M_M2_EM_WPC",min=45,max=49,equipment="Multi-ply",sex="M"}
    mm3rwpc = {name ="M_M3_R_WPC",min=50,max=54,equipment="Raw",sex="M"}
    mm3crwpc = {name ="M_M3_CR_WPC",min=50,max=54,equipment=["Raw","Wraps"],sex="M"}
    mm3swpc = {name ="M_M3_ES_WPC",min=50,max=54,equipment="Single-ply",sex="M"}
    mm3mwpc = {name ="M_M3_EM_WPC",min=50,max=54,equipment="Multi-ply",sex="M"}
    mm4rwpc = {name ="M_M4_R_WPC",min=55,max=59,equipment="Raw",sex="M"}
    mm4crwpc = {name ="M_M4_CR_WPC",min=55,max=59,equipment=["Raw","Wraps"],sex="M"}
    mm4swpc = {name ="M_M4_ES_WPC",min=55,max=59,equipment="Single-ply",sex="M"}
    mm4mwpc = {name ="M_M4_EM_WPC",min=55,max=59,equipment="Multi-ply",sex="M"}
    mm5rwpc = {name ="M_M5_R_WPC",min=60,max=64,equipment="Raw",sex="M"}
    mm5crwpc = {name ="M_M5_CR_WPC",min=60,max=64,equipment=["Raw","Wraps"],sex="M"}
    mm5swpc = {name ="M_M5_ES_WPC",min=60,max=64,equipment="Single-ply",sex="M"}
    mm5mwpc = {name ="M_M5_EM_WPC",min=60,max=64,equipment="Multi-ply",sex="M"}
    mm6rwpc = {name ="M_M6_R_WPC",min=65,max=69,equipment="Raw",sex="M"}
    mm6crwpc = {name ="M_M6_CR_WPC",min=65,max=69,equipment=["Raw","Wraps"],sex="M"}
    mm6swpc = {name ="M_M6_ES_WPC",min=65,max=69,equipment="Single-ply",sex="M"}
    mm6mwpc = {name ="M_M6_EM_WPC",min=65,max=69,equipment="Multi-ply",sex="M"}
    mm7rwpc = {name ="M_M7_R_WPC",min=70,max=74,equipment="Raw",sex="M"}
    mm7crwpc = {name ="M_M7_CR_WPC",min=70,max=74,equipment=["Raw","Wraps"],sex="M"}
    mm7swpc = {name ="M_M7_ES_WPC",min=70,max=74,equipment="Single-ply",sex="M"}
    mm7mwpc = {name ="M_M7_EM_WPC",min=70,max=74,equipment="Multi-ply",sex="M"}
    mm8rwpc = {name ="M_M8_CR_WPC",min=75,max=79,equipment="Raw",sex="M"}
    mm8crwpc = {name ="M_M8_R_WPC",min=75,max=79,equipment=["Raw","Wraps"],sex="M"}
    mm8swpc = {name ="M_M8_ES_WPC",min=75,max=79,equipment="Single-ply",sex="M"}
    mm8mwpc = {name ="M_M8_EM_WPC",min=75,max=79,equipment="Multi-ply",sex="M"}
    mm9rwpc = {name ="M_M9_R_WPC",min=80,max=999,equipment="Raw",sex="M"}
    mm9crwpc = {name ="M_M9_CR_WPC",min=80,max=999,equipment=["Raw","Wraps"],sex="M"}
    mm9swpc = {name ="M_M9_ES_WPC",min=80,max=999,equipment="Single-ply",sex="M"}
    mm9mwpc = {name ="M_M9_EM_WPC",min=80,max=999,equipment="Multi-ply",sex="M"}
    mmt1rwpc = {name ="M_T1_R_WPC",min=13,max=15,equipment="Raw",sex="M"}
    mmt1crwpc = {name ="M_T1_CR_WPC",min=13,max=15,equipment=["Raw","Wraps"],sex="M"}
    mmt1swpc = {name ="M_T1_ES_WPC",min=13,max=15,equipment="Single-ply",sex="M"}
    mmt1mwpc = {name ="M_T1_EM_WPC",min=13,max=15,equipment="Multi-ply",sex="M"}
    mmt2rwpc = {name ="M_T2_R_WPC",min=16,max=17,equipment="Raw",sex="M"}
    mmt2crwpc = {name ="M_T2_CR_WPC",min=16,max=17,equipment=["Raw","Wraps"],sex="M"}
    mmt2swpc = {name ="M_T2_ES_WPC",min=16,max=17,equipment="Single-ply",sex="M"}
    mmt2mwpc = {name ="M_T2_EM_WPC",min=16,max=17,equipment="Multi-ply",sex="M"}
    mmt3rwpc = {name ="M_T3_R_WPC",min=18,max=19,equipment="Raw",sex="M"}
    mmt3crwpc = {name ="M_T3_CR_WPC",min=18,max=19,equipment=["Raw","Wraps"],sex="M"}
    mmt3swpc = {name ="M_T3_ES_WPC",min=18,max=19,equipment="Single-ply",sex="M"}
    mmt3mwpc = {name ="M_T3_EM_WPC",min=18,max=19,equipment="Multi-ply",sex="M"}
    mjrwpc = {name ="M_J_R_WPC",min=20,max=23,equipment="Raw",sex="M"}
    mjcrwpc = {name ="M_J_CR_WPC",min=20,max=23,equipment=["Raw","Wraps"],sex="M"}
    mjswpc = {name ="M_J_ES_WPC",min=20,max=23,equipment="Single-ply",sex="M"}
    mjmwpc = {name ="M_J_EM_WPC",min=20,max=23,equipment="Multi-ply",sex="M"}
    msrwpc = {name ="M_S_R_WPC",min=33,max=39,equipment="Raw",sex="M"}
    mscrwpc = {name ="M_S_CR_WPC",min=33,max=39,equipment=["Raw","Wraps"],sex="M"}
    msswpc = {name ="M_S_ES_WPC",min=33,max=39,equipment="Single-ply",sex="M"}
    msmwpc = {name ="M_S_EM_WPC",min=33,max=39,equipment="Multi-ply",sex="M"}

    forwpc = {name ="F_O_R_WPC",min=0,max=999,equipment="Raw",sex="F"}
    focrwpc = {name ="F_O_CR_WPC",min=0,max=999,equipment=["Raw","Wraps"],sex="F"}
    foswpc = {name ="F_O_ES_WPC",min=0,max=999,equipment="Single-ply",sex="F"}
    fomwpc = {name ="F_O_EM_WPC",min=0,max=999,equipment="Multi-ply",sex="F"}
    fm1rwpc = {name ="F_M1_R_WPC",min=40,max=44,equipment="Raw",sex="F"}
    fm1crwpc = {name ="F_M1_CR_WPC",min=40,max=44,equipment=["Raw","Wraps"],sex="F"}
    fm1swpc = {name ="F_M1_ES_WPC",min=40,max=44,equipment="Single-ply",sex="F"}
    fm1mwpc = {name ="F_M1_EM_WPC",min=40,max=44,equipment="Multi-ply",sex="F"}
    fm2rwpc = {name ="F_M2_R_WPC",min=45,max=49,equipment="Raw",sex="F"}
    fm2crwpc = {name ="F_M2_CR_WPC",min=45,max=49,equipment=["Raw","Wraps"],sex="F"}
    fm2swpc = {name ="F_M2_ES_WPC",min=45,max=49,equipment="Single-ply",sex="F"}
    fm2mwpc = {name ="F_M2_EM_WPC",min=45,max=49,equipment="Multi-ply",sex="F"}
    fm3rwpc = {name ="F_M3_R_WPC",min=50,max=54,equipment="Raw",sex="F"}
    fm3crwpc = {name ="F_M3_CR_WPC",min=50,max=54,equipment=["Raw","Wraps"],sex="F"}
    fm3swpc = {name ="F_M3_ES_WPC",min=50,max=54,equipment="Single-ply",sex="F"}
    fm3mwpc = {name ="F_M3_EM_WPC",min=50,max=54,equipment="Multi-ply",sex="F"}
    fm4rwpc = {name ="F_M4_R_WPC",min=55,max=59,equipment="Raw",sex="F"}
    fm4crwpc = {name ="F_M4_CR_WPC",min=55,max=59,equipment=["Raw","Wraps"],sex="F"}
    fm4swpc = {name ="F_M4_ES_WPC",min=55,max=59,equipment="Single-ply",sex="F"}
    fm4mwpc = {name ="F_M4_EM_WPC",min=55,max=59,equipment="Multi-ply",sex="F"}
    fm5rwpc = {name ="F_M5_R_WPC",min=60,max=64,equipment="Raw",sex="F"}
    fm5crwpc = {name ="F_M5_CR_WPC",min=60,max=64,equipment=["Raw","Wraps"],sex="F"}
    fm5swpc = {name ="F_M5_ES_WPC",min=60,max=64,equipment="Single-ply",sex="F"}
    fm5mwpc = {name ="F_M5_EM_WPC",min=60,max=64,equipment="Multi-ply",sex="F"}
    fm6rwpc = {name ="F_M6_R_WPC",min=65,max=69,equipment="Raw",sex="F"}
    fm6crwpc = {name ="F_M6_CR_WPC",min=65,max=69,equipment=["Raw","Wraps"],sex="F"}
    fm6swpc = {name ="F_M6_ES_WPC",min=65,max=69,equipment="Single-ply",sex="F"}
    fm6mwpc = {name ="F_M6_EM_WPC",min=65,max=69,equipment="Multi-ply",sex="F"}
    fm7rwpc = {name ="F_M7_R_WPC",min=70,max=74,equipment="Raw",sex="F"}
    fm7crwpc = {name ="F_M7_CR_WPC",min=70,max=74,equipment=["Raw","Wraps"],sex="F"}
    fm7swpc = {name ="F_M7_ES_WPC",min=70,max=74,equipment="Single-ply",sex="F"}
    fm7mwpc = {name ="F_M7_EM_WPC",min=70,max=74,equipment="Multi-ply",sex="F"}
    fm8rwpc = {name ="F_M8_R_WPC",min=75,max=79,equipment="Raw",sex="F"}
    fm8crwpc = {name ="F_M8_CR_WPC",min=75,max=79,equipment=["Raw","Wraps"],sex="F"}
    fm8swpc = {name ="F_M8_ES_WPC",min=75,max=79,equipment="Single-ply",sex="F"}
    fm8mwpc = {name ="F_M8_EM_WPC",min=75,max=79,equipment="Multi-ply",sex="F"}
    fm9rwpc = {name ="F_M9_R_WPC",min=80,max=999,equipment="Raw",sex="F"}
    fm9crwpc = {name ="F_M9_CR_WPC",min=80,max=999,equipment=["Raw","Wraps"],sex="F"}
    fm9swpc = {name ="F_M9_ES_WPC",min=80,max=999,equipment="Single-ply",sex="F"}
    fm9mwpc = {name ="F_M9_EM_WPC",min=80,max=999,equipment="Multi-ply",sex="F"}
    fmt1rwpc = {name ="F_T1_R_WPC",min=13,max=15,equipment="Raw",sex="F"}
    fmt1crwpc = {name ="F_T1_CR_WPC",min=13,max=15,equipment=["Raw","Wraps"],sex="F"}
    fmt1swpc = {name ="F_T1_ES_WPC",min=13,max=15,equipment="Single-ply",sex="F"}
    fmt1mwpc = {name ="F_T1_EM_WPC",min=13,max=15,equipment="Multi-ply",sex="F"}
    fmt2rwpc = {name ="F_T2_R_WPC",min=16,max=17,equipment="Raw",sex="F"}
    fmt2crwpc = {name ="F_T2_CR_WPC",min=16,max=17,equipment=["Raw","Wraps"],sex="F"}
    fmt2swpc = {name ="F_T2_ES_WPC",min=16,max=17,equipment="Single-ply",sex="F"}
    fmt2mwpc = {name ="F_T2_EM_WPC",min=16,max=17,equipment="Multi-ply",sex="F"}
    fmt3rwpc = {name ="F_T3_R_WPC",min=18,max=19,equipment="Raw",sex="F"}
    fmt3crwpc = {name ="F_T3_CR_WPC",min=18,max=19,equipment=["Raw","Wraps"],sex="F"}
    fmt3swpc = {name ="F_T3_ES_WPC",min=18,max=19,equipment="Single-ply",sex="F"}
    fmt3mwpc = {name ="F_T3_EM_WPC",min=18,max=19,equipment="Multi-ply",sex="F"}
    fjrwpc = {name ="F_J_R_WPC",min=20,max=23,equipment="Raw",sex="F"}
    fjcrwpc = {name ="F_J_CR_WPC",min=20,max=23,equipment=["Raw","Wraps"],sex="F"}
    fjswpc = {name ="F_J_ES_WPC",min=20,max=23,equipment="Single-ply",sex="F"}
    fjmwpc = {name ="F_J_EM_WPC",min=20,max=23,equipment="Multi-ply",sex="F"}
    fsrwpc = {name ="F_S_R_WPC",min=33,max=39,equipment="Raw",sex="F"}
    fscrwpc = {name ="F_S_CR_WPC",min=33,max=39,equipment=["Raw","Wraps"],sex="F"}
    fsswpc = {name ="F_S_ES_WPC",min=33,max=39,equipment="Single-ply",sex="F"}
    fsmwpc = {name ="F_S_EM_WPC",min=33,max=39,equipment="Multi-ply",sex="F"}
    # AWPC Divisions

    morawpc = {name ="M_O_R_AWPC",min=0,max=999,equipment="Raw",sex="M"}
    mocrawpc = {name ="M_O_CR_AWPC",min=0,max=999,equipment=["Raw","Wraps"],sex="M"}
    mosawpc = {name ="M_O_ES_AWPC",min=0,max=999,equipment="Single-ply",sex="M"}
    momawpc = {name ="M_O_EM_AWPC",min=0,max=999,equipment="Multi-ply",sex="M"}
    mm1rawpc = {name ="M_M1_R_AWPC",min=40,max=44,equipment="Raw",sex="M"}
    mm1crawpc = {name ="M_M1_CR_AWPC",min=40,max=44,equipment=["Raw","Wraps"],sex="M"}
    mm1sawpc = {name ="M_M1_ES_AWPC",min=40,max=44,equipment="Single-ply",sex="M"}
    mm1mawpc = {name ="M_M1_EM_AWPC",min=40,max=44,equipment="Multi-ply",sex="M"}
    mm2rawpc = {name ="M_M2_R_AWPC",min=45,max=49,equipment="Raw",sex="M"}
    mm2crawpc = {name ="M_M2_CR_AWPC",min=45,max=49,equipment=["Raw","Wraps"],sex="M"}
    mm2sawpc = {name ="M_M2_ES_AWPC",min=45,max=49,equipment="Single-ply",sex="M"}
    mm2mawpc = {name ="M_M2_EM_AWPC",min=45,max=49,equipment="Multi-ply",sex="M"}
    mm3rawpc = {name ="M_M3_R_AWPC",min=50,max=54,equipment="Raw",sex="M"}
    mm3crawpc = {name ="M_M3_CR_AWPC",min=50,max=54,equipment=["Raw","Wraps"],sex="M"}
    mm3sawpc = {name ="M_M3_ES_AWPC",min=50,max=54,equipment="Single-ply",sex="M"}
    mm3mawpc = {name ="M_M3_EM_AWPC",min=50,max=54,equipment="Multi-ply",sex="M"}
    mm4rawpc = {name ="M_M4_R_AWPC",min=55,max=59,equipment="Raw",sex="M"}
    mm4crawpc = {name ="M_M4_CR_AWPC",min=55,max=59,equipment=["Raw","Wraps"],sex="M"}
    mm4sawpc = {name ="M_M4_ES_AWPC",min=55,max=59,equipment="Single-ply",sex="M"}
    mm4mawpc = {name ="M_M4_EM_AWPC",min=55,max=59,equipment="Multi-ply",sex="M"}
    mm5rawpc = {name ="M_M5_R_AWPC",min=60,max=64,equipment="Raw",sex="M"}
    mm5crawpc = {name ="M_M5_CR_AWPC",min=60,max=64,equipment=["Raw","Wraps"],sex="M"}
    mm5sawpc = {name ="M_M5_ES_AWPC",min=60,max=64,equipment="Single-ply",sex="M"}
    mm5mawpc = {name ="M_M5_EM_AWPC",min=60,max=64,equipment="Multi-ply",sex="M"}
    mm6rawpc = {name ="M_M6_R_AWPC",min=65,max=69,equipment="Raw",sex="M"}
    mm6crawpc = {name ="M_M6_CR_AWPC",min=65,max=69,equipment=["Raw","Wraps"],sex="M"}
    mm6sawpc = {name ="M_M6_ES_AWPC",min=65,max=69,equipment="Single-ply",sex="M"}
    mm6mawpc = {name ="M_M6_EM_AWPC",min=65,max=69,equipment="Multi-ply",sex="M"}
    mm7rawpc = {name ="M_M7_R_AWPC",min=70,max=74,equipment="Raw",sex="M"}
    mm7crawpc = {name ="M_M7_CR_AWPC",min=70,max=74,equipment=["Raw","Wraps"],sex="M"}
    mm7sawpc = {name ="M_M7_ES_AWPC",min=70,max=74,equipment="Single-ply",sex="M"}
    mm7mawpc = {name ="M_M7_EM_AWPC",min=70,max=74,equipment="Multi-ply",sex="M"}
    mm8rawpc = {name ="M_M8_R_AWPC",min=75,max=79,equipment="Raw",sex="M"}
    mm8crawpc = {name ="M_M8_CR_AWPC",min=75,max=79,equipment=["Raw","Wraps"],sex="M"}
    mm8sawpc = {name ="M_M8_ES_AWPC",min=75,max=79,equipment="Single-ply",sex="M"}
    mm8mawpc = {name ="M_M8_EM_AWPC",min=75,max=79,equipment="Multi-ply",sex="M"}
    mm9rawpc = {name ="M_M9_R_AWPC",min=80,max=999,equipment="Raw",sex="M"}
    mm9crawpc = {name ="M_M9_CR_AWPC",min=80,max=999,equipment=["Raw","Wraps"],sex="M"}
    mm9sawpc = {name ="M_M9_ES_AWPC",min=80,max=999,equipment="Single-ply",sex="M"}
    mm9mawpc = {name ="M_M9_EM_AWPC",min=80,max=999,equipment="Multi-ply",sex="M"}
    mmt1rawpc = {name ="M_T1_R_AWPC",min=13,max=15,equipment="Raw",sex="M"}
    mmt1crawpc = {name ="M_T1_CR_AWPC",min=13,max=15,equipment=["Raw","Wraps"],sex="M"}
    mmt1sawpc = {name ="M_T1_ES_AWPC",min=13,max=15,equipment="Single-ply",sex="M"}
    mmt1mawpc = {name ="M_T1_EM_AWPC",min=13,max=15,equipment="Multi-ply",sex="M"}
    mmt2rawpc = {name ="M_T2_R_AWPC",min=16,max=17,equipment="Raw",sex="M"}
    mmt2crawpc = {name ="M_T2_CR_AWPC",min=16,max=17,equipment=["Raw","Wraps"],sex="M"}
    mmt2sawpc = {name ="M_T2_ES_AWPC",min=16,max=17,equipment="Single-ply",sex="M"}
    mmt2mawpc = {name ="M_T2_EM_AWPC",min=16,max=17,equipment="Multi-ply",sex="M"}
    mmt3rawpc = {name ="M_T3_R_AWPC",min=18,max=19,equipment="Raw",sex="M"}
    mmt3crawpc = {name ="M_T3_CR_AWPC",min=18,max=19,equipment=["Raw","Wraps"],sex="M"}
    mmt3sawpc = {name ="M_T3_ES_AWPC",min=18,max=19,equipment="Single-ply",sex="M"}
    mmt3mawpc = {name ="M_T3_EM_AWPC",min=18,max=19,equipment="Multi-ply",sex="M"}
    mjrawpc = {name ="M_J_R_AWPC",min=20,max=23,equipment="Raw",sex="M"}
    mjcrawpc = {name ="M_J_CR_AWPC",min=20,max=23,equipment=["Raw","Wraps"],sex="M"}
    mjsawpc = {name ="M_J_ES_AWPC",min=20,max=23,equipment="Single-ply",sex="M"}
    mjmawpc = {name ="M_J_EM_AWPC",min=20,max=23,equipment="Multi-ply",sex="M"}
    msrawpc = {name ="M_S_R_AWPC",min=33,max=39,equipment="Raw",sex="M"}
    mscrawpc = {name ="M_S_CR_AWPC",min=33,max=39,equipment=["Raw","Wraps"],sex="M"}
    mssawpc = {name ="M_S_ES_AWPC",min=33,max=39,equipment="Single-ply",sex="M"}
    msmawpc = {name ="M_S_EM_AWPC",min=33,max=39,equipment="Multi-ply",sex="M"}

    forawpc = {name ="F_O_R_AWPC",min=0,max=999,equipment="Raw",sex="F"}
    focrawpc = {name ="F_O_CR_AWPC",min=0,max=999,equipment=["Raw","Wraps"],sex="F"}
    fosawpc = {name ="F_O_ES_AWPC",min=0,max=999,equipment="Single-ply",sex="F"}
    fomawpc = {name ="F_O_EM_AWPC",min=0,max=999,equipment="Multi-ply",sex="F"}
    fm1rawpc = {name ="F_M1_R_AWPC",min=40,max=44,equipment="Raw",sex="F"}
    fm1crawpc = {name ="F_M1_CR_AWPC",min=40,max=44,equipment=["Raw","Wraps"],sex="F"}
    fm1sawpc = {name ="F_M1_ES_AWPC",min=40,max=44,equipment="Single-ply",sex="F"}
    fm1mawpc = {name ="F_M1_EM_AWPC",min=40,max=44,equipment="Multi-ply",sex="F"}
    fm2rawpc = {name ="F_M2_R_AWPC",min=45,max=49,equipment="Raw",sex="F"}
    fm2crawpc = {name ="F_M2_CR_AWPC",min=45,max=49,equipment=["Raw","Wraps"],sex="F"}
    fm2sawpc = {name ="F_M2_ES_AWPC",min=45,max=49,equipment="Single-ply",sex="F"}
    fm2mawpc = {name ="F_M2_EM_AWPC",min=45,max=49,equipment="Multi-ply",sex="F"}
    fm3rawpc = {name ="F_M3_R_AWPC",min=50,max=54,equipment="Raw",sex="F"}
    fm3crawpc = {name ="F_M3_CR_AWPC",min=50,max=54,equipment=["Raw","Wraps"],sex="F"}
    fm3sawpc = {name ="F_M3_ES_AWPC",min=50,max=54,equipment="Single-ply",sex="F"}
    fm3mawpc = {name ="F_M3_EM_AWPC",min=50,max=54,equipment="Multi-ply",sex="F"}
    fm4rawpc = {name ="F_M4_R_AWPC",min=55,max=59,equipment="Raw",sex="F"}
    fm4crawpc = {name ="F_M4_CR_AWPC",min=55,max=59,equipment=["Raw","Wraps"],sex="F"}
    fm4sawpc = {name ="F_M4_ES_AWPC",min=55,max=59,equipment="Single-ply",sex="F"}
    fm4mawpc = {name ="F_M4_EM_AWPC",min=55,max=59,equipment="Multi-ply",sex="F"}
    fm5rawpc = {name ="F_M5_R_AWPC",min=60,max=64,equipment="Raw",sex="F"}
    fm5crawpc = {name ="F_M5_CR_AWPC",min=60,max=64,equipment=["Raw","Wraps"],sex="F"}
    fm5sawpc = {name ="F_M5_ES_AWPC",min=60,max=64,equipment="Single-ply",sex="F"}
    fm5mawpc = {name ="F_M5_EM_AWPC",min=60,max=64,equipment="Multi-ply",sex="F"}
    fm6rawpc = {name ="F_M6_R_AWPC",min=65,max=69,equipment="Raw",sex="F"}
    fm6crawpc = {name ="F_M6_CR_AWPC",min=65,max=69,equipment=["Raw","Wraps"],sex="F"}
    fm6sawpc = {name ="F_M6_ES_AWPC",min=65,max=69,equipment="Single-ply",sex="F"}
    fm6mawpc = {name ="F_M6_EM_AWPC",min=65,max=69,equipment="Multi-ply",sex="F"}
    fm7rawpc = {name ="F_M7_R_AWPC",min=70,max=74,equipment="Raw",sex="F"}
    fm7crawpc = {name ="F_M7_CR_AWPC",min=70,max=74,equipment=["Raw","Wraps"],sex="F"}
    fm7sawpc = {name ="F_M7_ES_AWPC",min=70,max=74,equipment="Single-ply",sex="F"}
    fm7mawpc = {name ="F_M7_EM_AWPC",min=70,max=74,equipment="Multi-ply",sex="F"}
    fm8rawpc = {name ="F_M8_R_AWPC",min=75,max=79,equipment="Raw",sex="F"}
    fm8crawpc = {name ="F_M8_CR_AWPC",min=75,max=79,equipment=["Raw","Wraps"],sex="F"}
    fm8sawpc = {name ="F_M8_ES_AWPC",min=75,max=79,equipment="Single-ply",sex="F"}
    fm8mawpc = {name ="F_M8_EM_AWPC",min=75,max=79,equipment="Multi-ply",sex="F"}
    fm9rawpc = {name ="F_M9_R_AWPC",min=80,max=999,equipment="Raw",sex="F"}
    fm9crawpc = {name ="F_M9_CR_AWPC",min=80,max=999,equipment=["Raw","Wraps"],sex="F"}
    fm9sawpc = {name ="F_M9_ES_AWPC",min=80,max=999,equipment="Single-ply",sex="F"}
    fm9mawpc = {name ="F_M9_EM_AWPC",min=80,max=999,equipment="Multi-ply",sex="F"}
    fmt1rawpc = {name ="F_T1_R_AWPC",min=13,max=15,equipment="Raw",sex="F"}
    fmt1crawpc = {name ="F_T1_CR_AWPC",min=13,max=15,equipment=["Raw","Wraps"],sex="F"}
    fmt1sawpc = {name ="F_T1_ES_AWPC",min=13,max=15,equipment="Single-ply",sex="F"}
    fmt1mawpc = {name ="F_T1_EM_AWPC",min=13,max=15,equipment="Multi-ply",sex="F"}
    fmt2rawpc = {name ="F_T2_R_AWPC",min=16,max=17,equipment="Raw",sex="F"}
    fmt2crawpc = {name ="F_T2_CR_AWPC",min=16,max=17,equipment=["Raw","Wraps"],sex="F"}
    fmt2sawpc = {name ="F_T2_ES_AWPC",min=16,max=17,equipment="Single-ply",sex="F"}
    fmt2mawpc = {name ="F_T2_EM_AWPC",min=16,max=17,equipment="Multi-ply",sex="F"}
    fmt3rawpc = {name ="F_T3_R_AWPC",min=18,max=19,equipment="Raw",sex="F"}
    fmt3crawpc = {name ="F_T3_CR_AWPC",min=18,max=19,equipment=["Raw","Wraps"],sex="F"}
    fmt3sawpc = {name ="F_T3_ES_AWPC",min=18,max=19,equipment="Single-ply",sex="F"}
    fmt3mawpc = {name ="F_T3_EM_AWPC",min=18,max=19,equipment="Multi-ply",sex="F"}
    fjrawpc = {name ="F_J_R_AWPC",min=20,max=23,equipment="Raw",sex="F"}
    fjcrawpc = {name ="F_J_CR_AWPC",min=20,max=23,equipment=["Raw","Wraps"],sex="F"}
    fjsawpc = {name ="F_J_ES_AWPC",min=20,max=23,equipment="Single-ply",sex="F"}
    fjmawpc = {name ="F_J_EM_AWPC",min=20,max=23,equipment="Multi-ply",sex="F"}
    fsrawpc = {name ="F_S_R_AWPC",min=33,max=39,equipment="Raw",sex="F"}
    fscrawpc = {name ="F_S_CR_AWPC",min=33,max=39,equipment=["Raw","Wraps"],sex="F"}
    fssawpc = {name ="F_S_ES_AWPC",min=33,max=39,equipment="Single-ply",sex="F"}
    fsmawpc = {name ="F_S_EM_AWPC",min=33,max=39,equipment="Multi-ply",sex="F"}

[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["0000-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","9999-01-01"]
    sex = "F"

[exemptions]
