# Configuration for CRPEBA.

[divisions]
    o = {name ="O", min=0, max=999}
    y = {name ="Y", min=0, max=12}
    t = {name ="T", min=13, max=19}
    t1 = {name ="T1", min=13, max=15}
    t2 = {name ="T2", min=16, max=17}
    t3 = {name ="T3", min=18, max=19}
    j = {name ="J", min=20, max=23}
    m1 = {name ="M1", min=40, max=49}
    m2 = {name ="M2", min=50, max=59}
    m3 = {name ="M3", min=60, max=69}
    m5559 = {name ="M4", min=55, max=59}
    m6064 = {name ="M5", min=60, max=64}
    m6569 = {name ="M6", min=65, max=69}
    m7074 = {name ="M7", min=70, max=74}
    m7579 = {name ="M8", min=75, max=79}

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","9999-12-31"]
    sex = "F"

[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["0000-01-01","9999-12-31"]
    sex = "M"

[weightclasses.youth_M]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["0000-01-01","9999-12-31"]
    sex = "M"
    divisions = ["Y"]

[exemptions]
