[divisions]
    open = {name ="Open",min=0,max=999}
 
[weightclasses.default_M]
    classes = ["75","90","105"]
    date_range=["0000-01-01","9999-01-01"]
    sex = "M"

[exemptions]
    1501 = ["ExemptWeightClassConsistency"]
    1601 = ["ExemptWeightClassConsistency"]
    1801 = ["ExemptWeightClassConsistency"]
