[divisions]
    amopen = {name ="Amateur Open",min=0,max=999}
    proopen = {name ="Pro Open",min=0,max=999}
    military = {name ="Military",min=0,max=999}

[weightclasses.default_M]
    classes = ["60","70","80","90","100","110","120","140","140+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["50","60","70","80","90","90+"]
    date_range=["1900-01-01","9999-01-01"]
    sex = "F"


[exemptions]
